# ==================================================
# DirectX11APIResource の CMakeLists.txt
# ==================================================

# サブディレクトリーを追加
add_subdirectory(00_Object)
add_subdirectory(01_Struct)
add_subdirectory(02_Loader)
add_subdirectory(03_Manager)
add_subdirectory(04_Factory)
